spring.application.name=LoanManagementSystem

spring.datasource.url = jdbc:postgresql://localhost:5433/nya
spring.datasource.driverClasssName = org.postgresql.Driver
spring.datasource.username = postgres
spring.datasource.password = Kuldeep@16

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
